name: Backend CI

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  test:
    runs-on: ubuntu-latest

    services:
      db:
        image: postgres:13
        env:
          POSTGRES_USER: postgres
          POSTGRES_PASSWORD: postgres
        ports:
          - 5432:5432
        options: >-
          --health-cmd="pg_isready -U postgres"
          --health-interval=10s
          --health-timeout=5s
          --health-retries=5

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Ruby
        uses: ruby/setup-ruby@v1
        with:
          ruby-version: 3.2.2

      - name: Install dependencies
        working-directory: backend
        run: |
          gem install bundler
          bundle install

      - name: Set environment to test
        run: echo "RAILS_ENV=test" >> $GITHUB_ENV

      - name: Set up database
        working-directory: backend
        run: |
          cp config/database.yml.ci config/database.yml
          bin/rails db:create db:migrate

      - name: Run tests
        working-directory: backend
        run: bundle exec rspec

  deploy:
    needs: test
    runs-on: ubuntu-latest
    steps:
      - name: Trigger Render Deployment
        env:
          RENDER_API_KEY: ${{ secrets.RENDER_API_KEY }}
        run: |
          echo "Starting Render Deployment..."
          curl -v -X POST "https://api.render.com/v1/services/srv-ctct0jpopnds73anu9lg/deploys" \
          -H "Authorization: Bearer $RENDER_API_KEY"
          echo "Render Deployment Trigger Complete."
